// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: orderItem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Order     *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Sku       *SKU                   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity  int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *OrderItem) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderItem) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderItemCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order    *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Sku      *SKU   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderItemCreateRequest) Reset() {
	*x = OrderItemCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemCreateRequest) ProtoMessage() {}

func (x *OrderItemCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderItemCreateRequest) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemCreateRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderItemCreateRequest) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *OrderItemCreateRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderItemCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderItem *OrderItem `protobuf:"bytes,1,opt,name=order_item,json=orderItem,proto3" json:"order_item,omitempty"`
}

func (x *OrderItemCreateResponse) Reset() {
	*x = OrderItemCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemCreateResponse) ProtoMessage() {}

func (x *OrderItemCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderItemCreateResponse) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemCreateResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type OrderItemUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Order    *Order `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Sku      *SKU   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity int64  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderItemUpdateRequest) Reset() {
	*x = OrderItemUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemUpdateRequest) ProtoMessage() {}

func (x *OrderItemUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemUpdateRequest.ProtoReflect.Descriptor instead.
func (*OrderItemUpdateRequest) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItemUpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *OrderItemUpdateRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderItemUpdateRequest) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *OrderItemUpdateRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderItemUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderItem *OrderItem `protobuf:"bytes,1,opt,name=order_item,json=orderItem,proto3" json:"order_item,omitempty"`
}

func (x *OrderItemUpdateResponse) Reset() {
	*x = OrderItemUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemUpdateResponse) ProtoMessage() {}

func (x *OrderItemUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemUpdateResponse.ProtoReflect.Descriptor instead.
func (*OrderItemUpdateResponse) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItemUpdateResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type OrderItemDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *OrderItemDeleteRequest) Reset() {
	*x = OrderItemDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemDeleteRequest) ProtoMessage() {}

func (x *OrderItemDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemDeleteRequest.ProtoReflect.Descriptor instead.
func (*OrderItemDeleteRequest) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{5}
}

func (x *OrderItemDeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type OrderItemDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderItemDeleteResponse) Reset() {
	*x = OrderItemDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemDeleteResponse) ProtoMessage() {}

func (x *OrderItemDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemDeleteResponse.ProtoReflect.Descriptor instead.
func (*OrderItemDeleteResponse) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{6}
}

type OrderItemGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *OrderItemGetRequest) Reset() {
	*x = OrderItemGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemGetRequest) ProtoMessage() {}

func (x *OrderItemGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemGetRequest.ProtoReflect.Descriptor instead.
func (*OrderItemGetRequest) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{7}
}

func (x *OrderItemGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type OrderItemGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderItem *OrderItem `protobuf:"bytes,1,opt,name=order_item,json=orderItem,proto3" json:"order_item,omitempty"`
}

func (x *OrderItemGetResponse) Reset() {
	*x = OrderItemGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemGetResponse) ProtoMessage() {}

func (x *OrderItemGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemGetResponse.ProtoReflect.Descriptor instead.
func (*OrderItemGetResponse) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{8}
}

func (x *OrderItemGetResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type OrderItemListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderItemListRequest) Reset() {
	*x = OrderItemListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemListRequest) ProtoMessage() {}

func (x *OrderItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemListRequest.ProtoReflect.Descriptor instead.
func (*OrderItemListRequest) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{9}
}

type OrderItemListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderItems []*OrderItem `protobuf:"bytes,1,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
}

func (x *OrderItemListResponse) Reset() {
	*x = OrderItemListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderItem_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemListResponse) ProtoMessage() {}

func (x *OrderItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderItem_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemListResponse.ProtoReflect.Descriptor instead.
func (*OrderItemListResponse) Descriptor() ([]byte, []int) {
	return file_orderItem_proto_rawDescGZIP(), []int{10}
}

func (x *OrderItemListResponse) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

var File_orderItem_proto protoreflect.FileDescriptor

var file_orderItem_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x73, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x4b, 0x55,
	0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x76, 0x0a, 0x16, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x4b, 0x55, 0x52, 0x03,
	0x73, 0x6b, 0x75, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x4a, 0x0a, 0x17, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x8a, 0x01, 0x0a, 0x16,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x4b, 0x55, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x4a, 0x0a, 0x17, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x22, 0x2c, 0x0a, 0x16, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a,
	0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x16, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x15, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xf0, 0x02, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x69, 0x73, 0x74, 0x69, 0x61, 0x6e, 0x63,
	0x6c, 0x6c, 0x2f, 0x71, 0x72, 0x70, 0x61, 0x79, 0x2d, 0x62, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orderItem_proto_rawDescOnce sync.Once
	file_orderItem_proto_rawDescData = file_orderItem_proto_rawDesc
)

func file_orderItem_proto_rawDescGZIP() []byte {
	file_orderItem_proto_rawDescOnce.Do(func() {
		file_orderItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_orderItem_proto_rawDescData)
	})
	return file_orderItem_proto_rawDescData
}

var file_orderItem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orderItem_proto_goTypes = []interface{}{
	(*OrderItem)(nil),               // 0: proto.OrderItem
	(*OrderItemCreateRequest)(nil),  // 1: proto.OrderItemCreateRequest
	(*OrderItemCreateResponse)(nil), // 2: proto.OrderItemCreateResponse
	(*OrderItemUpdateRequest)(nil),  // 3: proto.OrderItemUpdateRequest
	(*OrderItemUpdateResponse)(nil), // 4: proto.OrderItemUpdateResponse
	(*OrderItemDeleteRequest)(nil),  // 5: proto.OrderItemDeleteRequest
	(*OrderItemDeleteResponse)(nil), // 6: proto.OrderItemDeleteResponse
	(*OrderItemGetRequest)(nil),     // 7: proto.OrderItemGetRequest
	(*OrderItemGetResponse)(nil),    // 8: proto.OrderItemGetResponse
	(*OrderItemListRequest)(nil),    // 9: proto.OrderItemListRequest
	(*OrderItemListResponse)(nil),   // 10: proto.OrderItemListResponse
	(*Order)(nil),                   // 11: proto.Order
	(*SKU)(nil),                     // 12: proto.SKU
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_orderItem_proto_depIdxs = []int32{
	11, // 0: proto.OrderItem.order:type_name -> proto.Order
	12, // 1: proto.OrderItem.sku:type_name -> proto.SKU
	13, // 2: proto.OrderItem.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: proto.OrderItem.updated_at:type_name -> google.protobuf.Timestamp
	11, // 4: proto.OrderItemCreateRequest.order:type_name -> proto.Order
	12, // 5: proto.OrderItemCreateRequest.sku:type_name -> proto.SKU
	0,  // 6: proto.OrderItemCreateResponse.order_item:type_name -> proto.OrderItem
	11, // 7: proto.OrderItemUpdateRequest.order:type_name -> proto.Order
	12, // 8: proto.OrderItemUpdateRequest.sku:type_name -> proto.SKU
	0,  // 9: proto.OrderItemUpdateResponse.order_item:type_name -> proto.OrderItem
	0,  // 10: proto.OrderItemGetResponse.order_item:type_name -> proto.OrderItem
	0,  // 11: proto.OrderItemListResponse.order_items:type_name -> proto.OrderItem
	1,  // 12: proto.OrderItemService.Create:input_type -> proto.OrderItemCreateRequest
	3,  // 13: proto.OrderItemService.Update:input_type -> proto.OrderItemUpdateRequest
	5,  // 14: proto.OrderItemService.Delete:input_type -> proto.OrderItemDeleteRequest
	7,  // 15: proto.OrderItemService.Get:input_type -> proto.OrderItemGetRequest
	9,  // 16: proto.OrderItemService.List:input_type -> proto.OrderItemListRequest
	2,  // 17: proto.OrderItemService.Create:output_type -> proto.OrderItemCreateResponse
	4,  // 18: proto.OrderItemService.Update:output_type -> proto.OrderItemUpdateResponse
	6,  // 19: proto.OrderItemService.Delete:output_type -> proto.OrderItemDeleteResponse
	8,  // 20: proto.OrderItemService.Get:output_type -> proto.OrderItemGetResponse
	10, // 21: proto.OrderItemService.List:output_type -> proto.OrderItemListResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_orderItem_proto_init() }
func file_orderItem_proto_init() {
	if File_orderItem_proto != nil {
		return
	}
	file_order_proto_init()
	file_sku_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_orderItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderItem_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItemListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orderItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderItem_proto_goTypes,
		DependencyIndexes: file_orderItem_proto_depIdxs,
		MessageInfos:      file_orderItem_proto_msgTypes,
	}.Build()
	File_orderItem_proto = out.File
	file_orderItem_proto_rawDesc = nil
	file_orderItem_proto_goTypes = nil
	file_orderItem_proto_depIdxs = nil
}
